---
- hosts : 172.31.18.51
  become : yes
  tasks :
   - include_tasks : myfile.yml
   
   - name : start webServers
     service :
      name : httpd
      state : stopped
     notify : copyfile


    
  #  - name: Download foo.conf
  #    ansible.builtin.get_url:
  #     url: http://example.com/path/file.conf
  #     dest: /etc/foo.conf
  #     force_basic_auth : yes
  #     notify : copyfile

        #if any change is there then only handlers will run from above task'(orange host)
  handlers :
   - name : copyfile
     copy :
      src : f1
      dest : /home/mayank/mytestFile


