---
- hosts : 172.31.18.53
  become : yes
  tasks :
   - include_tasks : myfile.yml
   - name : copy file
     copy :
      src : f1
      dest : /home/mayank/mytestFile
   - name : start webServers
     service :
      name : httpd
      state : started
      
    
   - name: Download foo.conf
     ansible.builtin.get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
      force_basic_auth : yes

