---
- name : download tomcat file
  get_url :
   url :  https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
   dest : /opt/apache-tomcat-9.0.89.tar.gz
   force_basic_auth : yes

# - name : create tomcat folder
#   file :
#    path: /opt/tomcat
#    state : directory

- name : extract tar file
  command : 
    cmd : tar -zvxf /opt/apache-tomcat-9.0.89.tar.gz -C /opt
    creates : /opt/apache-tomcat-9.0.89.tar.gz/LICENSE 
    # to extract only once .it will check this path whether exists or not and if exists then no need to extract
