---
- name : host-manager context file into all nodes
  template :
   src : templates/hostmanagercontext.j2
   dest : /opt/apache-tomcat-9.0.89/webapps/host-manager/META-INF/context.xml

- name : manager context file into all nodes
  template :
    src : templates/managercontext.j2
    dest : /opt/apache-tomcat-9.0.89/webapps/manager/META-INF/context.xml

- name : tomcat users file into all nodes
  template :
     src : templates/tomcatuser.j2
     dest : /opt/apache-tomcat-9.0.89/conf/tomcat-users.xml
